// Code generated by logcopter-gen; DO NOT EDIT.

package workflowv3database

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.scraper.pkg.testfixtures.workflowv3database")
