// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=none"
// @generated from file proto/scraper/runtime/sessionstream/v1/runtime_stream.proto (package scraper.runtime.sessionstream.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_proto_scraper_runtime_v1_events } from "../../v1/events_pb";

/**
 * Describes the file proto/scraper/runtime/sessionstream/v1/runtime_stream.proto.
 */
export const file_proto_scraper_runtime_sessionstream_v1_runtime_stream = /*@__PURE__*/
  fileDesc("Cjtwcm90by9zY3JhcGVyL3J1bnRpbWUvc2Vzc2lvbnN0cmVhbS92MS9ydW50aW1lX3N0cmVhbS5wcm90bxIgc2NyYXBlci5ydW50aW1lLnNlc3Npb25zdHJlYW0udjEiTwoaUHVibGlzaFJ1bnRpbWVFdmVudENvbW1hbmQSMQoFZXZlbnQYASABKAsyIi5zY3JhcGVyLnJ1bnRpbWUudjEuUnVudGltZUV2ZW50VjEiSQoUUnVudGltZUV2ZW50T2JzZXJ2ZWQSMQoFZXZlbnQYASABKAsyIi5zY3JhcGVyLnJ1bnRpbWUudjEuUnVudGltZUV2ZW50VjEiSQoUUnVudGltZUV2ZW50QXBwZW5kZWQSMQoFZXZlbnQYASABKAsyIi5zY3JhcGVyLnJ1bnRpbWUudjEuUnVudGltZUV2ZW50VjEiRwoSUnVudGltZUV2ZW50RW50aXR5EjEKBWV2ZW50GAEgASgLMiIuc2NyYXBlci5ydW50aW1lLnYxLlJ1bnRpbWVFdmVudFYxQmpaaGdpdGh1Yi5jb20vZ28tZ28tZ29sZW1zL3NjcmFwZXIvZ2VuL3Byb3RvL3NjcmFwZXIvcnVudGltZS9zZXNzaW9uc3RyZWFtL3YxO3NjcmFwZXJydW50aW1lc2Vzc2lvbnN0cmVhbXYxYgZwcm90bzM", [file_proto_scraper_runtime_v1_events]);

/**
 * Describes the message scraper.runtime.sessionstream.v1.PublishRuntimeEventCommand.
 * Use `create(PublishRuntimeEventCommandSchema)` to create a new message.
 */
export const PublishRuntimeEventCommandSchema = /*@__PURE__*/
  messageDesc(file_proto_scraper_runtime_sessionstream_v1_runtime_stream, 0);

/**
 * Describes the message scraper.runtime.sessionstream.v1.RuntimeEventObserved.
 * Use `create(RuntimeEventObservedSchema)` to create a new message.
 */
export const RuntimeEventObservedSchema = /*@__PURE__*/
  messageDesc(file_proto_scraper_runtime_sessionstream_v1_runtime_stream, 1);

/**
 * Describes the message scraper.runtime.sessionstream.v1.RuntimeEventAppended.
 * Use `create(RuntimeEventAppendedSchema)` to create a new message.
 */
export const RuntimeEventAppendedSchema = /*@__PURE__*/
  messageDesc(file_proto_scraper_runtime_sessionstream_v1_runtime_stream, 2);

/**
 * Describes the message scraper.runtime.sessionstream.v1.RuntimeEventEntity.
 * Use `create(RuntimeEventEntitySchema)` to create a new message.
 */
export const RuntimeEventEntitySchema = /*@__PURE__*/
  messageDesc(file_proto_scraper_runtime_sessionstream_v1_runtime_stream, 3);

