// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=none"
// @generated from file proto/scraper/runtime/sessionstream/v1/runtime_stream.proto (package scraper.runtime.sessionstream.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { RuntimeEventV1 } from "../../v1/events_pb";

/**
 * Describes the file proto/scraper/runtime/sessionstream/v1/runtime_stream.proto.
 */
export declare const file_proto_scraper_runtime_sessionstream_v1_runtime_stream: GenFile;

/**
 * PublishRuntimeEventCommand is submitted by scraper producers into the
 * sessionstream hub. The command handler normalizes the embedded runtime event
 * and emits a RuntimeEventObserved backend event in the same session.
 *
 * @generated from message scraper.runtime.sessionstream.v1.PublishRuntimeEventCommand
 */
export declare type PublishRuntimeEventCommand = Message<"scraper.runtime.sessionstream.v1.PublishRuntimeEventCommand"> & {
  /**
   * @generated from field: scraper.runtime.v1.RuntimeEventV1 event = 1;
   */
  event?: RuntimeEventV1 | undefined;
};

/**
 * Describes the message scraper.runtime.sessionstream.v1.PublishRuntimeEventCommand.
 * Use `create(PublishRuntimeEventCommandSchema)` to create a new message.
 */
export declare const PublishRuntimeEventCommandSchema: GenMessage<PublishRuntimeEventCommand>;

/**
 * RuntimeEventObserved is the canonical backend event consumed by scraper
 * runtime-event projections.
 *
 * @generated from message scraper.runtime.sessionstream.v1.RuntimeEventObserved
 */
export declare type RuntimeEventObserved = Message<"scraper.runtime.sessionstream.v1.RuntimeEventObserved"> & {
  /**
   * @generated from field: scraper.runtime.v1.RuntimeEventV1 event = 1;
   */
  event?: RuntimeEventV1 | undefined;
};

/**
 * Describes the message scraper.runtime.sessionstream.v1.RuntimeEventObserved.
 * Use `create(RuntimeEventObservedSchema)` to create a new message.
 */
export declare const RuntimeEventObservedSchema: GenMessage<RuntimeEventObserved>;

/**
 * RuntimeEventAppended is the UI event sent to clients when a runtime event is
 * projected for live display.
 *
 * @generated from message scraper.runtime.sessionstream.v1.RuntimeEventAppended
 */
export declare type RuntimeEventAppended = Message<"scraper.runtime.sessionstream.v1.RuntimeEventAppended"> & {
  /**
   * @generated from field: scraper.runtime.v1.RuntimeEventV1 event = 1;
   */
  event?: RuntimeEventV1 | undefined;
};

/**
 * Describes the message scraper.runtime.sessionstream.v1.RuntimeEventAppended.
 * Use `create(RuntimeEventAppendedSchema)` to create a new message.
 */
export declare const RuntimeEventAppendedSchema: GenMessage<RuntimeEventAppended>;

/**
 * RuntimeEventEntity is the hydratable timeline entity stored in the
 * sessionstream projection store for runtime-event snapshots.
 *
 * @generated from message scraper.runtime.sessionstream.v1.RuntimeEventEntity
 */
export declare type RuntimeEventEntity = Message<"scraper.runtime.sessionstream.v1.RuntimeEventEntity"> & {
  /**
   * @generated from field: scraper.runtime.v1.RuntimeEventV1 event = 1;
   */
  event?: RuntimeEventV1 | undefined;
};

/**
 * Describes the message scraper.runtime.sessionstream.v1.RuntimeEventEntity.
 * Use `create(RuntimeEventEntitySchema)` to create a new message.
 */
export declare const RuntimeEventEntitySchema: GenMessage<RuntimeEventEntity>;

