// Code generated by logcopter-gen; DO NOT EDIT.

package manifest

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.scraper.pkg.sites.manifest")
