// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts,import_extension=none"
// @generated from file proto/scraper/runtime/v1/events.proto (package scraper.runtime.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file proto/scraper/runtime/v1/events.proto.
 */
export declare const file_proto_scraper_runtime_v1_events: GenFile;

/**
 * @generated from message scraper.runtime.v1.RuntimeEventV1
 */
export declare type RuntimeEventV1 = Message<"scraper.runtime.v1.RuntimeEventV1"> & {
  /**
   * @generated from field: uint32 schema_version = 1;
   */
  schemaVersion: number;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * @generated from field: scraper.runtime.v1.RuntimeEventSource source = 3;
   */
  source: RuntimeEventSource;

  /**
   * @generated from field: string component = 4;
   */
  component: string;

  /**
   * @generated from field: scraper.runtime.v1.RuntimeEventKind kind = 5;
   */
  kind: RuntimeEventKind;

  /**
   * @generated from field: scraper.runtime.v1.RuntimeEventSeverity severity = 6;
   */
  severity: RuntimeEventSeverity;

  /**
   * @generated from field: google.protobuf.Timestamp occurred_at = 7;
   */
  occurredAt?: Timestamp | undefined;

  /**
   * @generated from field: string message = 8;
   */
  message: string;

  /**
   * @generated from field: string workflow_id = 9;
   */
  workflowId: string;

  /**
   * @generated from field: string op_id = 10;
   */
  opId: string;

  /**
   * @generated from field: string site = 11;
   */
  site: string;

  /**
   * @generated from field: string queue = 12;
   */
  queue: string;

  /**
   * @generated from field: string worker_id = 13;
   */
  workerId: string;

  /**
   * @generated from field: string request_id = 14;
   */
  requestId: string;

  /**
   * @generated from field: string artifact_id = 15;
   */
  artifactId: string;

  /**
   * @generated from field: map<string, string> labels = 16;
   */
  labels: { [key: string]: string };

  /**
   * @generated from field: google.protobuf.Struct payload = 17;
   */
  payload?: JsonObject | undefined;
};

/**
 * Describes the message scraper.runtime.v1.RuntimeEventV1.
 * Use `create(RuntimeEventV1Schema)` to create a new message.
 */
export declare const RuntimeEventV1Schema: GenMessage<RuntimeEventV1>;

/**
 * @generated from enum scraper.runtime.v1.RuntimeEventSource
 */
export enum RuntimeEventSource {
  /**
   * @generated from enum value: RUNTIME_EVENT_SOURCE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: RUNTIME_EVENT_SOURCE_SCHEDULER = 1;
   */
  SCHEDULER = 1,

  /**
   * @generated from enum value: RUNTIME_EVENT_SOURCE_WORKER = 2;
   */
  WORKER = 2,

  /**
   * @generated from enum value: RUNTIME_EVENT_SOURCE_RUNNER = 3;
   */
  RUNNER = 3,

  /**
   * @generated from enum value: RUNTIME_EVENT_SOURCE_SERVER = 4;
   */
  SERVER = 4,

  /**
   * @generated from enum value: RUNTIME_EVENT_SOURCE_SUBMISSION = 5;
   */
  SUBMISSION = 5,

  /**
   * @generated from enum value: RUNTIME_EVENT_SOURCE_REQUEST = 6;
   */
  REQUEST = 6,
}

/**
 * Describes the enum scraper.runtime.v1.RuntimeEventSource.
 */
export declare const RuntimeEventSourceSchema: GenEnum<RuntimeEventSource>;

/**
 * @generated from enum scraper.runtime.v1.RuntimeEventSeverity
 */
export enum RuntimeEventSeverity {
  /**
   * @generated from enum value: RUNTIME_EVENT_SEVERITY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: RUNTIME_EVENT_SEVERITY_DEBUG = 1;
   */
  DEBUG = 1,

  /**
   * @generated from enum value: RUNTIME_EVENT_SEVERITY_INFO = 2;
   */
  INFO = 2,

  /**
   * @generated from enum value: RUNTIME_EVENT_SEVERITY_WARN = 3;
   */
  WARN = 3,

  /**
   * @generated from enum value: RUNTIME_EVENT_SEVERITY_ERROR = 4;
   */
  ERROR = 4,
}

/**
 * Describes the enum scraper.runtime.v1.RuntimeEventSeverity.
 */
export declare const RuntimeEventSeveritySchema: GenEnum<RuntimeEventSeverity>;

/**
 * @generated from enum scraper.runtime.v1.RuntimeEventKind
 */
export enum RuntimeEventKind {
  /**
   * @generated from enum value: RUNTIME_EVENT_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: RUNTIME_EVENT_KIND_WORKFLOW_CREATED = 1;
   */
  WORKFLOW_CREATED = 1,

  /**
   * @generated from enum value: RUNTIME_EVENT_KIND_WORKFLOW_UPDATED = 2;
   */
  WORKFLOW_UPDATED = 2,

  /**
   * @generated from enum value: RUNTIME_EVENT_KIND_WORKFLOW_CANCELED = 3;
   */
  WORKFLOW_CANCELED = 3,

  /**
   * @generated from enum value: RUNTIME_EVENT_KIND_OP_LEASED = 4;
   */
  OP_LEASED = 4,

  /**
   * @generated from enum value: RUNTIME_EVENT_KIND_OP_SUCCEEDED = 5;
   */
  OP_SUCCEEDED = 5,

  /**
   * @generated from enum value: RUNTIME_EVENT_KIND_OP_RETRIED = 6;
   */
  OP_RETRIED = 6,

  /**
   * @generated from enum value: RUNTIME_EVENT_KIND_OP_FAILED = 7;
   */
  OP_FAILED = 7,

  /**
   * @generated from enum value: RUNTIME_EVENT_KIND_QUEUE_RATE_LIMITED = 8;
   */
  QUEUE_RATE_LIMITED = 8,

  /**
   * @generated from enum value: RUNTIME_EVENT_KIND_WORKER_IDLE = 9;
   */
  WORKER_IDLE = 9,

  /**
   * @generated from enum value: RUNTIME_EVENT_KIND_SUBMISSION_ACCEPTED = 10;
   */
  SUBMISSION_ACCEPTED = 10,

  /**
   * @generated from enum value: RUNTIME_EVENT_KIND_SUBMISSION_REJECTED = 11;
   */
  SUBMISSION_REJECTED = 11,

  /**
   * @generated from enum value: RUNTIME_EVENT_KIND_REQUEST_RECEIVED = 12;
   */
  REQUEST_RECEIVED = 12,

  /**
   * @generated from enum value: RUNTIME_EVENT_KIND_REQUEST_SERVED = 13;
   */
  REQUEST_SERVED = 13,

  /**
   * @generated from enum value: RUNTIME_EVENT_KIND_LOG_LINE = 14;
   */
  LOG_LINE = 14,
}

/**
 * Describes the enum scraper.runtime.v1.RuntimeEventKind.
 */
export declare const RuntimeEventKindSchema: GenEnum<RuntimeEventKind>;

